version: "3.8"

services:
  redis:
    image: redis

  db:
    image: postgres:9.4

  vote:
    image: nginx:alpine
    ports:
      - "5000:80"

  worker:
    image: nginx:alpine

  result:
    image: nginx:alpine
    ports:
      - "5001:80"
